### ISSUE TITLE
[idea?] simulate events for netlify event triggered functions

### ISSUE THREAD

**Issue by sw-yx** [netlify/netlify-dev-plugin#106]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the expected behavior?**
help with local testing on netlify event triggered functions by firing them with mock data?

**Comment by ZoltanVeres** [comment]
Yes, +1 for this!

**Comment by sw-yx** [comment]
:) 

we are in the process of hiring people to build out netlify dev, i'll leave this to them to work out

**Comment by ZoltanVeres** [comment]
There is very few information about the event triggered functions, especially about the datastructure it gets passed in. I might be able to help if i get this information. I want to use it to invoke lighthouse-ci every time a new PR is generated.We want to use it in the official gatsby-netlifycms starter and prob. In netlifycms repo as well.

**Comment by sw-yx** [comment]
hmm, yeah, even i dont know that much. this is all we've got. https://www.netlify.com/docs/functions/#event-triggered-functions

**Comment by ZoltanVeres** [comment]
Posted a question to [Netlify Community](https://community.netlify.com/t/provide-more-information-about-event-triggered-functions/651) asking about more clarifications.  *fingers crossed!*

**Comment by sw-yx** [comment]
mock triggering functions locally

**Comment by sw-yx** [comment]
fyi added here https://github.com/netlify/netlify-dev-plugin/pull/213
