### ISSUE TITLE
Going to .live Server url causes error/fail on Netlify Dev

### ISSUE THREAD

**Issue by JacobDFrank** [netlify/netlify-dev-plugin#113]
`netlify dev --live` fails after going to designated Live Tunnel or .live Server

1. Run the command `netlify dev --live` and it goes through Gatsby build process.
2. Compilation on gatsby dev side is successful.
```
ℹ ｢wdm｣: Compiling...
 DONE  Compiled successfully in 61ms
```
3. I go to my loaded server `https://site-name-cf7b6c.netlify.live`
4. Get all these errors...
```
ℹ ｢wdm｣:
ℹ ｢wdm｣: Compiled successfully.
INFO[0020] Reconnecting to tunnel server
INFO[0030] finished client unary call                    error="rpc error: code = Unknown desc = Connection already stablished" grpc.code=Unknown grpc.method=Register grpc.service=tunnel.Tunnel grpc.time_ms=46.362 span.kind=client system=grpc
FATA[0030] can not register client                       error="rpc error: code = Unknown desc = Connection already stablished"
```

[my repo is here and made in gatsby](https://github.com/JacobDFrank/tawGatsby2-rearchitecture)
node v11.6.0 OSX 10.14.4

**Comment by sw-yx** [comment]
thanks for this - going to just roll this up into our netlify dev --live tracker issue.

**Comment by sw-yx** [comment]
hey Jacob, we've just updated our [live-tunnel system](https://github.com/netlify/live-tunnel).  If you run `netlify dev --live` again you should see `◈ Installing Live Tunnel Client` on the first run and you'll pick up the changes.

**Comment by calavera** [comment]
@JacobDFrank feel free to reopen if you're still seeing this problem.

**Comment by JacobDFrank** [comment]
It works, thanks!
