### ISSUE TITLE
ReferenceError: chalk is not defined

### ISSUE THREAD

**Issue by spezzino** [netlify/netlify-dev-plugin#118]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
ReferenceError is thrown

**- If the current behavior is a bug, please provide the steps to reproduce.**
run `netlify dev --live`
it triggers the build process, which is completed successfully.
After that it starts a tunnel
```
Connected!
Waiting for localhost:8000.
Connected!
ReferenceError: chalk is not defined
    at createTunnel (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/live-tunnel.js:14:75)
```

**- What is the expected behavior?**
Tunnel starts correctly

**- Please mention your node.js, and operating system version.**
nodejs v11.11.0
MacOS 10.14.3

**Comment by sw-yx** [comment]
fixed , thank you

**Comment by sw-yx** [comment]
fixed in https://github.com/netlify/cli/releases/tag/v2.11.7
