### ISSUE TITLE
Bug: netlify dev mangles base64 upload

### ISSUE THREAD

**Issue by sanderhahn** [netlify/netlify-dev-plugin#143]
**- What is the current behavior?**

Binary file upload base64 is mangled when uploaded to netlify dev. The same upload to a deployed site works correctly. The binary is a transparant png for demo purposes:

```bash
$ base64 pixel-transparent.png
iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGP6zwAAAgcBApocMXEAAAAASUVORK5CYII=
```

The function just displays the base64 data that is made available:

```javascript
exports.handler = async function (event, context) {
    return {
        statusCode: 200,
        body: JSON.stringify({
            base64: event.isBase64Encoded,
            data: event.body,
        }),
    };
};
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

Upload to netlify dev site:

```bash
$ curl -X POST -H "Content-Type: image/jpeg" --data-binary "@pixel-transparent.png" http://localhost:8888/.netlify/functions/body
{"base64":true,"data":"77+9UE5HDQoaCgAAAA1JSERSAAAAAQAAAAEIBAAAAO+/vRwMAgAAAAtJREFUeO+/vWPvv73vv70AAAIHAQLvv70cMXEAAAAASUVORO+/vUJg77+9"}
```

**- What is the expected behavior?**

Upload to deployed site:

```bash
$ curl -X POST -H "Content-Type: image/jpeg" --data-binary "@pixel-transparent.png" https://{site_id}.netlify.com/.netlify/functions/body
{"base64":true,"data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGP6zwAAAgcBApocMXEAAAAASUVORK5C"}
```

OS: mac
Node: v10.11.0

Thanks for making Netlify!
Works great :)

**Comment by sw-yx** [comment]
this sounds very similar to a thing we had in netlify-lambda: https://github.com/netlify/netlify-lambda/pull/68/files

i'm not going to work on this right now but will welcome PRs if you can figure it out. its probably going to be pretty similar and we may have just missed a detail or two. equivalent code is around here: https://github.com/netlify/netlify-dev-plugin/blob/bdd84895049bf0fb520f9cc87c828b6307f5243f/src/utils/serve-functions.js#L56
