### ISSUE TITLE
Live URL Returns 502 Error

### ISSUE THREAD

**Issue by alexmacarthur** [netlify/netlify-dev-plugin#158]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When I run `netlify dev --live`, the 'live' URL that is returned to me returns a 502 error consistently. For example: https://macarthur-a77436.netlify.live 

**- If the current behavior is a bug, please provide the steps to reproduce.**
* Run `netlify dev --live`.
* Navigate to the URL provided following "Server now ready on _____."
* See 502 error. 

**- What is the expected behavior?**
I expect the URL to not return a 502, but instead a live version of my local site. 

**- Please mention your node.js, and operating system version.**
OS: Mac Mojave
Node: LTS (10.15.3)

**Comment by calavera** [comment]
It looks like our servers cannot connect with your local computer. Can you run the command with the debug flag and attach the log file to the issue? that would help us debug the issue:

```
DEBUG=1 netlify dev --live
```

That should print lots of logs.

Can you also make sure you don't have a zombie process running? This command should tell you:

```
ps aux | grep tunnel-client
```

**Comment by alexmacarthur** [comment]
Ah... this turned out to be a firewall issue. Moving to a different network fixed the problem. Sorry about that! Closing this.
