### ISSUE TITLE
It looks like `settings.port` is undefined here:

### ISSUE THREAD

**Issue by sw-yx** [netlify/netlify-dev-plugin#162]
It looks like `settings.port` is undefined here:

https://github.com/netlify/netlify-dev-plugin/blob/master/src/commands/dev/index.js#L257

It might be caused by a wrong detector configuration

/cc @sw-yx

_Originally posted by @calavera in https://github.com/netlify/netlify-react-ui/pull/2820#issuecomment-486355939_

**Comment by calavera** [comment]
I think this only happens when we fallback to the static server.

**Comment by sw-yx** [comment]
no longer relevant
