### ISSUE TITLE
"spawn yarn ENOENT" using netlify dev

### ISSUE THREAD

**Issue by johnmryan** [netlify/netlify-dev-plugin#164]
`netlify dev --command="gatsby develop"` results in the following output:
```
◈ Netlify Dev ◈
◈ Injected build setting env var:  CLIENT_ID
... other things Injected
◈ Starting Netlify Dev with gatsby
Error: spawn yarn ENOENT
```

`npx gatsby develop` works fine.

**Comment by sw-yx** [comment]
something is very weird about your setup. lets condense it in this other isseu https://github.com/netlify/netlify-dev-plugin/issues/163
