### ISSUE TITLE
Improve code reloading with unbundled JS functions in multiple files

### ISSUE THREAD

**Issue by mjm** [netlify/netlify-dev-plugin#167]
**- Do you want to request a *feature* or report a *bug*?**

Feature (maybe a bug depending on currently intended behavior)

**- What is the current behavior?**

`netlify dev` with unbundled functions does not seem to reload code for local require()'d Node modules, but it would be nice if it did! 😄

I'm not sure, but I think it reloads the main .js file with the handler export, but if you factor out code into separate files, then you lose the reloading behavior and have to restart `netlify dev` to see your changes. Especially for Gatsby sites (which take a while to process), this really slows down development compared to using webpack with netlify-lambda.

**- Please mention your node.js, and operating system version.**

Node 11.13.0, macOS 10.14.4

**Comment by sw-yx** [comment]
agreed. you’re right about our file watch strategy.
