### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 'functions'

### ISSUE THREAD

**Issue by jakeherp** [netlify/netlify-dev-plugin#182]
I am trying to use `netlify dev` on a Gatsby project, but get the following error when running the command in my project:

```
Error: ENOENT: no such file or directory, scandir 'functions'
    at createHandler (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/utils/serve-functions.js:59:6)
    at serveFunctions (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/utils/serve-functions.js:242:16)
npm WARN lifecycle The node binary used for scripts is /var/folders/p6/py3zjppx39l4zjpqjh41pgxh0000gn/T/yarn--1557741659930-0.035928606088158066/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> agency@0.1.0 develop /Users/jacob/Development/agency
> GATSBY_GRAPHQL_IDE=playground gatsby develop
```

I have `gatsby-plugin-netlify` and `gatsby-plugin-netlify-cache` installed and also configured a `netlify.toml` file through the command line tool using `netlify init`, although my understanding is, that this would only be required for the continuous deploy, not for running the dev server on my local machine?

**Comment by sw-yx** [comment]
for the time being, just make an empty `functions` folder or you can also delete the `functions` config inside `netlify.toml`. this is on us, we need to iron this out better.
