### ISSUE TITLE
Create React App URL hides the correct Netlify URL

### ISSUE THREAD

**Issue by oliverjam** [netlify/netlify-dev-plugin#199]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug

**- What is the current behavior?**
Starting the dev sever with `netlify dev` logs `Server now ready on http://localhost:8888` very briefly.

<img width="832" alt="Screenshot 2019-06-10 at 15 05 29" src="https://user-images.githubusercontent.com/9408641/59201297-052f9000-8b92-11e9-85f9-1a8068dd29f5.png">

Then Create React App takes over, removes the old log and shows `http://localhost:3000`.

<img width="829" alt="Screenshot 2019-06-10 at 15 05 38" src="https://user-images.githubusercontent.com/9408641/59201328-17a9c980-8b92-11e9-8810-7f2f0aa50302.png">

If you aren't paying attention you'll miss the first one and spend ages refreshing port 3000 pointlessly attempting to get your lambda to run 🙃 

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. `npx create-react-app lambda-test`
1. `netlify create:functions testFn`
1. Make a request to `.netlify/functions/testFn` in the React app
1. `netlify dev` to start the server
1. Visit `localhost:3000` and see the request fail
1. Visit `localhost:8888` and see the request succeed

**- What is the expected behavior?**

Ideally Netlify should keep showing me the correct `netlify dev` server URL (`localhost:8888`) and hide the CRA one.

**- Please mention your node.js, and operating system version.**
```
node: 10.14.1
npm: 6.4.1
os: macOS 10.14.5 Mojave
```

**Edit:** I thought this might be my specific terminal app (Hyper) hiding away the previous output, but I just tested in the native Mac Terminal.app and it happens the same way

**Comment by sw-yx** [comment]
yes, this is due to CRA's rather annoying [clearConsole](https://github.com/facebook/create-react-app/issues/611). if you have a way around it let me know.

**Comment by oliverjam** [comment]
Ah that makes sense. Feel free to close this, since it's not really a Netlify bug.
