### ISSUE TITLE
Functions overview, more debugging info

### ISSUE THREAD

**Issue by bkniffler** [netlify/netlify-dev-plugin#209]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
No insights about what functions are recognized

I think it would help a ton if netlify dev gave a rough overview about what functions were found and their respective url endpoints. This would especially help since currently it is not super clear what function names are used, for example having a function in `functionfolder/api/index.js` with `functionfolder/api/package.json` having a name field "api", what name is used? Folder? Filename? Package json name field?

**Comment by sw-yx** [comment]
happy to consider that, but fyi theres no ambiguity with regards to naming. it -has- to be folder AND filename being the same.  example:

```
valid
---
functionfolder/api/api.js

invalid
---
functionfolder/api/index.js and no other files
functionfolder/api/package.json having a name field "api" and `api.js`
```

**Comment by bkniffler** [comment]
Would you consider changing the behaviour? I find it counterintuitive to not have /api/index.js work. This is my example function folder:

```
// Current
functions/hello-world.js
functions/api/api.js
functions/api/utils.js // <= just a utility library used by api.js
functions/apiV2/apiV2.js
Services: /hello-world, /api, /apiV2

// Node module resolution style
functions/hello-world.js
functions/api/index.js
functions/api/utils.js
functions/apiV2/index.js

Services: /hello-world, /api, /apiV2
```

**Comment by sw-yx** [comment]
@bkniffler lets just say that this exact topic has been debated internally :) and this behavior is what we have for now with no immediate plans to change. i will mention this issue again but personally i have learned to live with it.

**Comment by sw-yx** [comment]
`netlify functions:list` https://github.com/netlify/netlify-dev-plugin/pull/211
