### ISSUE TITLE
netlify.toml does not seem to be respected?

### ISSUE THREAD

**Issue by surma** [netlify/netlify-dev-plugin#226]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Redirects, headers and rewrites in my `netlify.toml` don’t seem to be handled by the dev server

**- If the current behavior is a bug, please provide the steps to reproduce.**
Take any project with a `netlify.toml`, use the dev server and see if headers or redirects are working.

**- What is the expected behavior?**
They should be working.

**- Please mention your node.js, and operating system version.**
```
$ netlify version
netlify-cli/2.11.29 darwin-x64 node-v12.2.0
```

**Comment by sw-yx** [comment]
transferred to dev-plugin repo 

redirects do need some work, however they should be at least MOSTLY working. if they dont seem to work AT ALL that is very unexpected since i use them plenty.



possibly related https://github.com/netlify/netlify-dev-plugin/issues/203

**Comment by surma** [comment]
Yup, @DavidWells helped me and I was just holding it wrong.

I confused the `netlify.toml` with `_headers` and put it in the `build` directory, not in the root. That’s it. So closing this. Thanks y’all!
