### ISSUE TITLE
Remove `netlify` dependency

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-dev-plugin#241]
`netlify` (the JavaScript client) is listed as a production dependency, but it does not seem to be used anywhere. It is indirectly used by some dependencies, but not directly. Can you confirm this can be safely removed from the `package.json` `dependencies`?

**Comment by RaeesBhatti** [comment]
This library has been moved into the CLI https://github.com/netlify/cli/pull/396. We're planning to  archive this repo.

**Comment by RaeesBhatti** [comment]
@ehmicky Apologies for confusion

**Comment by ehmicky** [comment]
Thanks for the quick response @raeesbhatti!
